#include my-autohotkey-scripts/hotstrings/abbreviations.ahk
#include my-autohotkey-scripts/hotstrings/autocorrect.ahk
#include my-autohotkey-scripts/hotstrings/codetags.ahk
#include my-autohotkey-scripts/hotstrings/coding.ahk
#include my-autohotkey-scripts/hotstrings/date.ahk
#include my-autohotkey-scripts/hotstrings/etc.ahk
#include my-autohotkey-scripts/hotstrings/languages.ahk
#include my-autohotkey-scripts/hotstrings/logging.ahk
#include my-autohotkey-scripts/hotstrings/symbols.ahk
